### ISSUE TITLE
FEATURE REQUEST: Hide PulseAudio audio selectors when the plugin is in use

### ISSUE THREAD

**Issue by orowith2os** [dimtpap/obs-pipewire-audio-capture#13]
When using the plugin, it works beautifully, although it's a bit cluttered to see PulseAudio and then PipeWIre audio selectors rather than just PipeWire. 
My suggestion is to hide the PulseAudio options when the plugin is in use.

Unrelated suggestion: add a note to put the plugin inside of `~/.var/app/com.obsproject.Studio/config/obs-studio/plugins/` if using the flatpak of OBS Studio.

**Comment by orowith2os** [comment]
I've verified that the options do not disappear if access to PulseAudio is disabled in the flatpak permissions.

**Comment by dimtpap** [comment]
Do you mean the PulseAudio sources in the sources list? I really can't do anything about that. Plugins can't mess around with other plugins' stuff. I will add that Flatpak note though

**Comment by orowith2os** [comment]
I do mean the PulseAudio sources. If they can't be hidden, I'll make a suggestion to upstream to implement this plugin by default and/or remove the PulseAudio settings at a user toggle.

**Comment by dimtpap** [comment]
I'm already working on it here https://github.com/obsproject/obs-studio/pull/6207
