### ISSUE TITLE
Plugin fails to initialize in flatpak OBS

### ISSUE THREAD

**Issue by XDevC512L** [dimtpap/obs-pipewire-audio-capture#15]
In the flatpak version of OBS unless its given `--filesystem=xdg-run/pipewire-0` permission the plugin will fail when adding a new audio capture with the following error:
```
warning: [pipewire] Error creating PipeWire core
error: Failed to create source 'Application Audio Capture (PipeWire)'!
```
I'm not an expert on the Linux audio stack, and I don't know if there is some limitation regarding pipewire audio access through xdg-portal (i checked that easyeffects flatpak also has this permission granted) but in that case it would be good to include this workaround on the README until this gets merged on the main OBS repository.

**Comment by dimtpap** [comment]
> I don't know if there is some limitation regarding pipewire audio access through xdg-portal

Access to the system's main PipeWire remote is limited, xdg-desktop-portal provides controlled access to a limited part of it. Unfortunately there is no portal for audio yet, only for screencasting.
