### ISSUE TITLE
Feature Request: Add app to visible Allow and Block list

### ISSUE THREAD

**Issue by jarrard** [dimtpap/obs-pipewire-audio-capture#20]
Thinking it be neat if there was a list box in this plugin and you could allow or block apps via button that adds it to a list which has Application/processname with allowed or blocked to the right of it depending on which button you pressed (Allow/Block buttons).

Maybe this would also be good for being able to include apps/processes into the list that are not present in the auto detect system?

**Comment by jarrard** [comment]
True but only 1 at a time from what I can see. How would you add multiple? is there a way to do app1:app2:app3?

**Comment by dimtpap** [comment]
You can just add more sources, each capturing a different app

**Comment by jarrard** [comment]
> 

True, didn't think of that. I'll just close this since that seems like a decent solution. 

However a bug I have atm is it doesn't remember my selection each time I start OBS up. But that is a different issue.

**Comment by Enovale** [comment]
This solution doesn't really work if you want to exclude multiple apps, also I don't think having a ton of sources is very organized. I would like there to be a way to add multiple apps to the list, if even just with comma separation.
