### ISSUE TITLE
Feature Request: New Option for display sound source.

### ISSUE THREAD

**Issue by VladimirMrzv** [dimtpap/obs-pipewire-audio-capture#21]
On old build plugin show app or game name, now show "wine64-preloader", can you add option to choose how to display.

Add function to choose sound source without open properties, add here
![Выделение_047](https://user-images.githubusercontent.com/81020401/182394688-115b5d7a-06fa-4fc0-b798-5747b92518ad.png)

**Comment by dimtpap** [comment]
Making the list show without opening the properties requires modifying OBS itself, it can't be done through a plugin
