### ISSUE TITLE
Application Audio Capture: Capture all apps except this one does not persist across OBS restarts

### ISSUE THREAD

**Issue by flexiondotorg** [dimtpap/obs-pipewire-audio-capture#23]
Thank you very much for `obs-pipewire-audio-capture` 🙇 It has resolved several audio-related issues in my OBS Studio setup and helped simplify my scene/source composition.

## Expected behaviour

When adding an `Application Audio Capture (PipeWire)` source and checking `Capture all apps except this one`, the option will persist across restarts of OBS Studio.

## Actual behaviour

When adding an `Application Audio Capture (PipeWire)` source and checking `Capture all apps except this one`, it is only effective for the current OBS Studio session. Upon restarting OBS Studio `Capture all apps except this one` is unchecked and needs to be re-enabled.

## Configuration

- OBS Studio 28.0.1
- obs-pipewire-audio-capture 1.0.4
- Ubuntu MATE 22.04.1
  - pipewire 0.3.48
  - wireplumber 0.4.8

PipeWire was manually installed as follows:

`apt-get install gstreamer1.0-pipewire pipewire-audio-client-libraries wireplumber`

**Comment by flexiondotorg** [comment]
@dimtpap Thanks for the fix. I see in #17 you provided a link daily build including the fix. Any chance you have a daily build that includes this fix?

**Comment by dimtpap** [comment]
Went ahead and released it as a new version https://github.com/dimtpap/obs-pipewire-audio-capture/releases/tag/1.0.5

**Comment by flexiondotorg** [comment]
Thank you!
