### ISSUE TITLE
A linux native game (Crypt of the necrodancer) doesnt show up as an audio source.

### ISSUE THREAD

**Issue by AmyRoxwell** [dimtpap/obs-pipewire-audio-capture#25]
Crypt of the Necrodancer has a linux version (https://store.steampowered.com/app/247080/Crypt_of_the_NecroDancer/) but for some reason it doesnt display when I try to select it as an audio source, this doesnt happen with other native linux games like Half-Life 2 or L4D2. 
In other hand, when you run the game using proton then you can select it as an audio source just fine.

**Comment by dimtpap** [comment]
Open the game and run `pw-cli info all > pwinfo.txt`, then post the `pwinfo.txt` file here, it will be in the directory you ran the command in.

**Comment by dimtpap** [comment]
If [SteamDB](https://steamdb.info/app/247080/info/) is correct and the game uses OpenAL for audio, open the game's properties in your Steam library and in "LAUNCH OPTIONS" put `ALSOFT_DRIVERS=pulse %command%` and see if it works

**Comment by AmyRoxwell** [comment]
Sorry for the late answer, 
> If [SteamDB](https://steamdb.info/app/247080/info/) is correct and the game uses OpenAL for audio, open the game's properties in your Steam library and in "LAUNCH OPTIONS" put `ALSOFT_DRIVERS=pulse %command%` and see if it works
>
The solution you posted actually fixed it, now it shows up in the plugin properties and it works properly!
> Open the game and run `pw-cli info all > pwinfo.txt` in a terminal, then post the `pwinfo.txt` file here, it will be in the directory you ran the command in.
>
I tried to use the command but the terminal throws this error: `$ pw-cli info all > pwinfo.txt
info: unsupported type PipeWire:Interface:Profiler`

**Comment by dimtpap** [comment]
> I tried to use the command but the terminal throws this error: `$ pw-cli info all > pwinfo.txt
> info: unsupported type PipeWire:Interface:Profiler`

It's just a warning, the command worked

**Comment by AmyRoxwell** [comment]
I see, so, should I close this issue as solved?

**Comment by dimtpap** [comment]
Post the `pwinfo.txt` file

**Comment by AmyRoxwell** [comment]
[pwinfo.txt](https://github.com/dimtpap/obs-pipewire-audio-capture/files/9590843/pwinfo.txt)

**Comment by dimtpap** [comment]
Yeah in its default configuration the game uses Jack, apps using Jack can have complex port configurations where not all of their output ports should be sent out to speakers/captures (take Ardour for example) so the capture can't really work with them
