### ISSUE TITLE
1.0.5 release doesn't work with obs 27

### ISSUE THREAD

**Issue by e00E** [dimtpap/obs-pipewire-audio-capture#26]
Not sure if intentional but should be documented somewhere because it is confusing. The current newest release 1.0.5 loads as a plugin according to the obs log but doesn't add any new sources. With the 1.0.4 release I see the new sources. This is probably related to the obs version I am on which is `27.2.4-2` from the arch linux package which isn't updated to 28 yet.

**Comment by HookedBehemoth** [comment]
I get that too with this log message three times
`00:52:28.007: obs_register_source: Tried to register obs_source_info with size 400 which is more than libobs currently supports (392)`

**Comment by dimtpap** [comment]
Not intentional, updated the release to include a build compatible with OBS 27
