### ISSUE TITLE
Feature request: filter source

### ISSUE THREAD

**Issue by ogmkp** [dimtpap/obs-pipewire-audio-capture#27]
Hello and thank you for this plugin.

Is it possible to make it in the source filters, in case of I want to output the sound of a source before or after other plugin in the filters list? And make this output persistent (not disappearing when the media/source is not played).

I'm using OBS 27.2.4.

**Comment by dimtpap** [comment]
This is out of scope of this plugin but I believe [this](https://github.com/exeldro/obs-audio-monitor) does something similar to what you want, though I'm not sure if it supports Linux

**Comment by reznyt** [comment]
I need this as well. The audio monitor plugin does not support linux - only mac and windows. There doesn't seem to be any solution whatsoever for linux users. Would you please consider expanding the scope of this project?
