### ISSUE TITLE
obs-pipewire-audio-capture not outputting audio

### ISSUE THREAD

**Issue by float3** [dimtpap/obs-pipewire-audio-capture#28]
I am using the obs-pipewire-audio-capture plugin in OBS Studio, but it is not outputting any audio. I have selected it as an audio input source, but no audio is being captured or outputted.

OBS Studio - 28.1.2-2 (linux)
Linux 6.0.11-arch1-1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux

latest version of obs-pipewire-audio-capture

**Comment by Melechtna** [comment]
> it was a wireplumber issue

PLEASE be more specific, because I'm having the same issue.

**Comment by float3** [comment]
sorry I don't remember
