### ISSUE TITLE
Implementing audio exception flag

### ISSUE THREAD

**Issue by NicKoehler** [dimtpap/obs-pipewire-audio-capture#3]
Is possible to implement a flag that inverts the functionality excluding an application to be recorded?
I saw that option in [this windows plugin](https://github.com/bozbez/win-capture-audio)

![image](https://user-images.githubusercontent.com/53040044/154856333-6807b45a-d759-44ad-8f15-bce8754c6446.png)

Thanks

**Comment by Qufyy** [comment]
It is but it would require quite some rework. You can use tools like [Helvum](https://gitlab.freedesktop.org/pipewire/helvum) to completely customize the routing of your applications.

**Comment by NicKoehler** [comment]
Thanks for the suggestion, I'm currently using [Carla](https://kx.studio/Applications:Carla), but my main issue is that I need to set it up every time I want to stream or record something. Most of the times all I need is to record everything except one single application, that's why I asked.

**Comment by dimtpap** [comment]
Added in 1.0.0
