### ISSUE TITLE
NixOS straight up not working

### ISSUE THREAD

**Issue by Melechtna** [dimtpap/obs-pipewire-audio-capture#30]
So, using the provided package for this, it doesn't work at all, the plugin doesn't even load, OBS doesn't even acknowledge its existence in the console. When loading it the binary way, absolutely no audio what so ever gets recorded or streamed. Not sure what to do for it, I am using wireplumber.

**Comment by dimtpap** [comment]
I do not maintain the Nix package, I don't know what's wrong there. Use the manual installation method and run OBS Studio with `obs --verbose`. Add a source and configure it. Then run `pw-dump > pw-dump.txt` in a shell and post the `pw-dump.txt` that gets created, as well as the latest log from OBS Studio.

**Comment by Melechtna** [comment]
[obs.txt](https://github.com/dimtpap/obs-pipewire-audio-capture/files/11804026/obs.txt)
[pw-dump.txt](https://github.com/dimtpap/obs-pipewire-audio-capture/files/11804027/pw-dump.txt)

Here they are, and maybe you could also tell me why the virtual camera both fails to be detected by anything (it claims to start fine) and never requests elevated permissions like it did before? Honestly these are the only 2 issues I've run into with this system, so any help at all is much appreciated. From an initial glance, I can't see anything particularly egregious in the logs.

**Comment by dimtpap** [comment]
In the Advanced Audio Properties of the sources, are the audio tracks checked?

**Comment by Melechtna** [comment]
> 

I'm not ENTIRELY sure what you mean, but I don't think that's a thing anymore
![Screenshot_20230620_141804](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/81296467/a4a26bb2-ea00-4853-90f2-6ecaf6a792f7)
This is the only area they show up in the audio section

**Comment by Melechtna** [comment]
End me
![Screenshot_20230620_142021](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/81296467/5cab535e-decb-4c58-84b0-4dab3633fcf4)
None of the tracks were checked, it's fine
