### ISSUE TITLE
Can't select any applications

### ISSUE THREAD

**Issue by RadiantHero6** [dimtpap/obs-pipewire-audio-capture#32]
Downloaded the plugin and it opens just fine, using PipeWire. 

When loading the games: Tropico 6, Grandia 2 and booting up obs, no programs show up in the application field, and pressing the drop down arrow doesn't show anything.

![image](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/90285213/318f28f9-04c1-4d72-9c0c-cf094d497574)

**Comment by dimtpap** [comment]
Do other programs work? For example your browser

**Comment by RadiantHero6** [comment]
> Do other programs work? For example your browser

No, nothing shows up.

**Comment by dimtpap** [comment]
Check if you have WirePlumber and pipewire-pulse installed

**Comment by RadiantHero6** [comment]
When trying to install pipewire-pulse, I get this 

![image](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/90285213/ce5a690d-42b8-4d57-816c-66a7ac181a4c)

**Comment by dimtpap** [comment]
Most programs use PulseAudio to output sound. To make those available in PipeWire, pipewire-pulse acts as a replacement for the original PulseAudio system. You need it installed, so hit Yes, but check the following in case you've tweaked your PulseAudio system

https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Migrate-PulseAudio
https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Config-PulseAudio

**Comment by RadiantHero6** [comment]
Seems the page is down for now?

![image](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/90285213/89f7ddd9-0515-4e0b-bffc-a4497632a80b)
