### ISSUE TITLE
Feature and UI parity with win-capture-audio?

### ISSUE THREAD

**Issue by Nukley** [dimtpap/obs-pipewire-audio-capture#34]
https://github.com/bozbez/win-capture-audio
I found the UI and features of the latest beta build for this to be incredibly useful, and I was wondering if you would be able to add something similar? It basically had a list of programs you could specify, and you could set them all to either exclude, or include. I recommend firing up a windows 10/11 vm just to understand how it works in full.

**Comment by dimtpap** [comment]
See the [`multiple-apps-per-source`](https://github.com/dimtpap/obs-pipewire-audio-capture/tree/multiple-apps-per-source) branch and #24

**Comment by Nukley** [comment]
Oh, oops lol. Sorry about that, I guess I should have read the issues page more carefully.
