### ISSUE TITLE
Add ability to exclude multible applications from audio.

### ISSUE THREAD

**Issue by chikenpotpi** [dimtpap/obs-pipewire-audio-capture#35]
There doesnt seem to be any way to do it without duplicating the audio which is not preferable.
Maybe this already is possible so correct me if im wrong.

**Comment by dimtpap** [comment]
See the [`multiple-apps-per-source`](https://github.com/dimtpap/obs-pipewire-audio-capture/tree/multiple-apps-per-source) branch and #24
