### ISSUE TITLE
OBS Apllication Audio Capture

### ISSUE THREAD

**Issue by NezhaTheMyth** [dimtpap/obs-pipewire-audio-capture#36]
I use the application audio capture but it is reading from my desktop audio instead. as in i select it to only take audio from discord. it will take audio from discord but also spotify and any other application i have open.

**Comment by dimtpap** [comment]
Does version 1.1.0 work properly?

**Comment by NezhaTheMyth** [comment]
Yes 1.1.0 does work properly

**Comment by dimtpap** [comment]
What are the outputs of `pipewire --version` and `wireplumber --version`

**Comment by NezhaTheMyth** [comment]
pipewire 0.3.48   and it wouldnt give me an answer for wireplumber but i reinstalled and updated it

**Comment by dimtpap** [comment]
You should try to use a PipeWire version newer than 0.3.62 because of #17. By the PipeWire version I assume you're using a distro based on Ubuntu 22.04. If so, take a look at https://pipewire-debian.github.io/pipewire-debian/

**Comment by dimtpap** [comment]
This should be fixed since [1.1.3](https://github.com/dimtpap/obs-pipewire-audio-capture/releases/tag/1.1.3)
