### ISSUE TITLE
Virtual duplex devices are not detected

### ISSUE THREAD

**Issue by RoarkGit** [dimtpap/obs-pipewire-audio-capture#38]
I use Audio/Duplex devices for routing a bunch of inputs (e.g. microphone -> REAPER -> Duplex In; Duplex Out -> Discord), described [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-devices). These are not currently detected by this plugin.

I suspect the change would just be adding another condition to [this](https://github.com/dimtpap/obs-pipewire-audio-capture/blob/main/src/pipewire-audio-capture-device.c#L233) bit of code: `|| strcmp(media_class, "Audio/Duplex") == 0`

**Comment by dimtpap** [comment]
Should Duplex devices be shown both in the Input and Output capture sources?

**Comment by RoarkGit** [comment]
I think output is all that's needed. Consider these two duplex devices I have:

"Voice"
Microphone Input -> REAPER In -> Reaper Out -> Voice In, then Voice Out actually produces the sound

"Discord"
Discord Application Out -> Discord In, then Discord Out actually produces the sound

In all cases it's still the "output" end that is producing the sound to be captured. It wouldn't make sense to have OBS be feeding sound to the "input" side of things.

**Comment by RoarkGit** [comment]
Hmm, this doesn't seem to work as expected. I did this change locally as well last night to see, but wasn't sure if I did  something wrong. When adding the device, OBS reports no output sound. If I add the same source as output via PulseAudio (pipewire-pulseaudio) it does seem to work, though.

**Comment by dimtpap** [comment]
What's the configuration for your virtual devices?

**Comment by RoarkGit** [comment]
I'm trying with two different devices and neither seems to work:

```
pipewire.conf

# This is a loopback device, I have "Desktop" set as my default audio output.
# It plays back through my physical audio interface.
context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description "Desktop Loopback"
            audio.position = "[ FL FR ]"
            capture.props = {
                media.class = "Audio/Sink"
                node.name = "stream.desktop.in"
                node.description "Desktop"
            }
            playback.props = {
                node.name = "stream.desktop.out"
                node.target = "alsa_output.usb-Schiit_Audio_Schiit_Unison_Universal_Dac-00.analog-stereo"
            }
        }
    }
}

# This is the Voice duplex device.
context.objects = [
    {   factory = adapter
        args = {
            factory.name      = support.null-audio-sink
            node.name         = "stream.voice"
            node.description  = "Voice"
            media.class       = "Audio/Duplex"
            audio.position    = "MONO"
        }
    }
]
```
The first device is set up like this (shown via `qpwgraph` with one application feeding output into it):
![image](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/34554573/fa51ecfb-1954-4d07-8700-236b2e38fc1a)

The second device is set up like this (shown via `qpwgraph`):
![image](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/34554573/de61f7bb-d745-4591-99b1-4799853e8bee)

**Comment by dimtpap** [comment]
Try adding `audio.channels = (number of audio channels)` in `playback.props`

**Comment by RoarkGit** [comment]
No luck, and I do actually notice some strange behavior where the device keeps changing itself back to "Default."

![image](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/34554573/2c405e58-c2a1-4f0a-b254-20227f19303c)

This happens whenever I set the device to something else (in my case, "Desktop").

I can set it to different physical interfaces and it works fine, but any of the virtuals just get dropped and set to whatever the last physical interface was.

**Comment by dimtpap** [comment]
I got it to work after adding `audio.channels = "1"` in the args of the Voice duplex device and `audio.channels = "2"` in `capture.props` of the Desktop lookpback

**Comment by RoarkGit** [comment]
Interesting! That does appear to have done the trick. I've had this config going forever so haven't messed with it in awhile, I'll go read up on stuff again and see if there is something new / something I've missed that would have made this more obvious! Thanks for the help / quick fix.
