### ISSUE TITLE
Audio of captured apps stop playing on SIGSTOP

### ISSUE THREAD

**Issue by notpeelz** [dimtpap/obs-pipewire-audio-capture#39]
When I attach a debugger to obs, for as long as I don't resume execution, I can no longer hear the audio of captured apps through my speakers/headphones.
This can also be replicated by sending SIGSTOP to obs (i.e `pkill -e obs -STOP` and `pkill -e obs -CONT`).

### System info

```
distro: Arch Linux (x86-64)
kernel: Linux 6.6.1-arch1
obs: 30.0.0
pipewire: 0.3.85
obs-pipewire-audio-capture: 1.1.2
```

**Comment by dimtpap** [comment]
This happens due to the design of PipeWire, not a bug https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3509#note_2083124
