### ISSUE TITLE
Audio on "Application Audio Capture (PipeWire) is cutting in and out and crackling

### ISSUE THREAD

**Issue by pipoliviero** [dimtpap/obs-pipewire-audio-capture#43]
The audio on "Application Audio Capture (PipeWire)" is cutting in and out and crackling. The desktop audio track on that same recording is perfectly fine. The issue occurs with other applications/games including native games through non-flatpak steam.

PopOS 22.04 LTS
OBS (30.0.2, Flatpak)
pipewire-audio-capture (1.1.2)
Halo Infinite (Proton-GE 8, Steam Flatpak)

(Youtube seems to be editing the audio in some way because *most* of the crackling is gone but the gaps in the audio are still clear.)
Example: https://youtu.be/kXzIXV-Cfgc

**Comment by dimtpap** [comment]
Are you using your distribution's PipeWire package? From a quick search it's PipeWire 0.3.42, which is too old. Try with https://pipewire-debian.github.io/pipewire-debian/

**Comment by pipoliviero** [comment]
Issue only happens with video encoder AOM AV1. Once I switched to FFmpeg VAAPI HEVC the problem went away. Not really sure why. I have to admit I have no idea what I'm doing here, so if anyone else wants to explore that issue more in depth please do.

**Comment by dimtpap** [comment]
It sounds like some encoder problem of sorts. Considering it sounded different on YouTube too. My first guess was that the AV1 encoder is overloading your CPU but that doesn't make sense since the Audio Output Capture was working fine. Oh well
