### ISSUE TITLE
No Audio capture from support.null-audio-sink

### ISSUE THREAD

**Issue by marvin1099** [dimtpap/obs-pipewire-audio-capture#44]
So i have setup a few virtual devices but none of them can be captured (virt. speakers and mics)
So i use this config for virt. speakers in pipewire.conf.d:

    context.objects = [
        {   factory = adapter
            args = {
                factory.name     = support.null-audio-sink
                node.name        = "phone"
                media.class      = Audio/Sink
                audio.position   = [ FL FR ]
                adapter.auto-port-config = {
                    mode = dsp
                    monitor = true
                    position = preserve
                }
            }
        }
    ]
for virt. mics i use the config:

    context.objects = [
        {   factory = adapter
            args = {
                factory.name     = support.null-audio-sink
                node.name        = "micmirror"
                media.class      = Audio/Source/Virtual
                audio.position   = [ FL FR ]
                adapter.auto-port-config = {
                    mode = dsp
                    monitor = true
                    position = preserve
                }
            }
        }
    ]
Here is my obs log: 
[2024-01-13 10-28-03.txt](https://github.com/dimtpap/obs-pipewire-audio-capture/files/13927548/2024-01-13.10-28-03.txt)
And here is my pipewire setup, but its a bit messy and complex because i use a gaming and streaming pc and send the audio from the gaming pc to the streaming pc:
![Screenshot_20240113_103122](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/40715852/3091a18c-cb08-4cd3-9370-f152d23ed9c4)
As it says in the Title i seams that none of the virtual devices get selected, i can select alsa devices just fine.
Well to be exact selecting one of these virtual devices works in the obs plugin gui but it wont spawn anything in the pw graph.
Also when i then close the obs plugin gui it reverts to the last setting if a virtual device was selected.
There seemed to to a similar issue but I am on ne newest version of this plugin (1.1.2-2; build with the aur package) i also tryed the version 1.1.2 from github. Im on OBS version 30.0.2 (from the aur obs-studio-tytan652). If you need any more logs just say so. Any help is welcome.

**Comment by dimtpap** [comment]
Try adding `audio.channels = 2` in the properties of your sinks

**Comment by marvin1099** [comment]
yo mean like this in the config (i will try that):
context.objects = [
    {   factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "phone"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
            audio.channels = 2
            adapter.auto-port-config = {
                mode = dsp
                monitor = true
                position = preserve
            }
        }
    }
]

**Comment by marvin1099** [comment]
Jep that worked thanks
