### ISSUE TITLE
Unable to capture audio from applications despite dependencies being fulfilled

### ISSUE THREAD

**Issue by gPhantasm** [dimtpap/obs-pipewire-audio-capture#45]
The plugin does not show any applications, despite `pipewire`, `wireplumber`, `pipewire-pulse`, `pipewire-jack`, and `pipewire-alsa` being installed. Is there something else that I'm missing?
![image](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/115580700/00905207-1169-4e9b-a0a2-4e401de012fa)

**Comment by dimtpap** [comment]
Audio Output Capture is for capturing audio output devices. The source you're looking for is the "Application Audio Capture" source
