### ISSUE TITLE
Robotic Audio in Stream and Recording

### ISSUE THREAD

**Issue by CaptainKamikaZ** [dimtpap/obs-pipewire-audio-capture#46]
Here is a clip of my most recent stream:
https://youtu.be/dJd_FcjqK6Y

I'm capturing the audio of Discord while being in a call to add the audio of the other participants to the stream. The sound very frequently sounds robotic from this one source. This is the case in both the stream and in the recording.

System info: running Pipewire and Wireplumber on Linux Mint

**Comment by dimtpap** [comment]
What's the output of `pw-metadata -n settings`

**Comment by CaptainKamikaZ** [comment]
pw-metadata -n settings:
Found "settings" metadata 30
update: id:0 key:'log.level' value:'2' type:''
update: id:0 key:'clock.rate' value:'48000' type:''
update: id:0 key:'clock.allowed-rates' value:'[ 48000 ]' type:''
update: id:0 key:'clock.quantum' value:'1024' type:''
update: id:0 key:'clock.min-quantum' value:'16' type:''
update: id:0 key:'clock.max-quantum' value:'2048' type:''
update: id:0 key:'clock.force-quantum' value:'0' type:''
update: id:0 key:'clock.force-rate' value:'0' type:''

pipewire --version:
pipewire
Compiled with libpipewire 0.3.48
Linked with libpipewire 0.3.48

wireplumber --version:
Unknown option --version

**Comment by CaptainKamikaZ** [comment]
Since wireplumber didn't give me a version, I also checked the status of it.

systemctl --user status wireplumber:

● wireplumber.service - Multimedia Service Session Manager
     Loaded: loaded (/usr/lib/systemd/user/wireplumber.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-02-16 03:10:05 CST; 9h ago
   Main PID: 1944 (wireplumber)
      Tasks: 4 (limit: 38147)
     Memory: 7.3M
        CPU: 2.055s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/wireplumber.service
             └─1944 /usr/bin/wireplumber

Feb 16 03:10:05 justin-Mint systemd[1932]: Started Multimedia Service Session Manager.
Feb 16 03:10:05 justin-Mint wireplumber[1944]: Failed to set scheduler settings: Operation not permitted
Feb 16 03:10:05 justin-Mint wireplumber[1944]: SPA handle 'api.bluez5.enum.dbus' could not be loaded; is it installed?
Feb 16 03:10:05 justin-Mint wireplumber[1944]: PipeWire's BlueZ SPA missing or broken. Bluetooth not supported.
Feb 16 03:10:06 justin-Mint wireplumber[1944]: <WpSiAudioAdapter:0x557341f96040> Object activation aborted: proxy destroyed
Feb 16 03:10:06 justin-Mint wireplumber[1944]: <WpSiAudioAdapter:0x557341f96040> failed to activate item: Object activation aborted: proxy destroyed
Feb 16 12:54:42 justin-Mint wireplumber[1944]: SPA handle 'api.bluez5.enum.dbus' could not be loaded; is it installed?
Feb 16 12:54:42 justin-Mint wireplumber[1944]: PipeWire's BlueZ SPA missing or broken. Bluetooth not supported.

**Comment by dimtpap** [comment]
Try newer versions of PipeWire. Since you're on Mint this should work https://pipewire-debian.github.io/pipewire-debian/

**Comment by CaptainKamikaZ** [comment]
Ok, I went through that whole guide and reinstalled everything. I'll let you know how it turns out once I make another recording.

**Comment by CaptainKamikaZ** [comment]
Problem solved! Thank you very much!
