### ISSUE TITLE
Missing applications

### ISSUE THREAD

**Issue by MrNessuno** [dimtpap/obs-pipewire-audio-capture#48]
I tried to add some Applications but the plugins shows me only kwin_wayland, obs, wireplumber or xdg-desktop-portal.
I have several application opened as Firefox, Brave and Discord but I can't see any of them.
Am I doing something wrong?

```
pipewire --version  
pipewire
Compiled with libpipewire 1.0.3
Linked with libpipewire 1.0.3
wireplumber --version
wireplumber
Compiled with libwireplumber 0.4.17
Linked with libwireplumber 0.4.17
```

![obs-plugin](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/20603088/c1f55f86-f101-41ef-b688-0038fa47dfc8)

**Comment by slxdy** [comment]
Can you at the very least share your solution?
