### ISSUE TITLE
Publish to Flathub

### ISSUE THREAD

**Issue by deadmeu** [dimtpap/obs-pipewire-audio-capture#49]
Offering a Flathub distributed package would make this plugin easier to install for the OBS Flatpak.

https://github.com/obsproject/obs-studio/pull/6207 doesn't appear like it will be ready to merge any time soon, so it would be valuable to simplify the installation & update experience for users.

See https://github.com/flathub/com.obsproject.Studio.Plugin.OBSVkCapture for an example of a plugin published to Flathub.

**Comment by dimtpap** [comment]
This plugin requires the `--filesystem=xdg-run/pipewire-0` permission to be set for OBS Studio. Currently it is set by upstream, but it can be removed at anytime and break the plugin as they're transitioning to portals.

If Flatpak extensions can set additional flags on the host application then this can be considered, but I can't find anything for that in the [Flatpak](https://docs.flatpak.org/en/latest/extension.html) [documentation](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html#flatpak-manifest)

**Comment by boredsquirrel** [comment]
Hi, I just started the packaging as a flatpak, may be broken, dont really know what I am doing XD

https://github.com/boredsquirrel/com.obsproject.Studio.Plugin.PipewireAudioCapture

**Comment by dimtpap** [comment]
> If Flatpak extensions can set additional flags on the host application then this can be considered

They can't
