### ISSUE TITLE
Update claimed OBS version reqirement

### ISSUE THREAD

**Issue by CrimsonFork** [dimtpap/obs-pipewire-audio-capture#50]
Forum and Readme claims OBS minimum verseion required is 28, but 29.1.3 fails with the error
```
warning: obs_register_source: Tried to register obs_source_info with size 408 which is more than libobs currently supports (400)
```
while no such issue exists in 30.0.2.

**Comment by dimtpap** [comment]
Fixed in [1.1.4](https://github.com/dimtpap/obs-pipewire-audio-capture/releases/tag/1.1.4)
