### ISSUE TITLE
Build on openSUSE Tumbleweed installs to wrong location

### ISSUE THREAD

**Issue by hendersj** [dimtpap/obs-pipewire-audio-capture#51]
I built this plugin yesterday for my OBS build on openSUSE Tumbleweed, and the results of `sudo make install` copied `linux-pipewire-audio.so` to `/usr/lib/obs-plugins/` instead of to `/usr/lib64/obs-plugins/`, resulting it the plugin not showing up in obs.  Moving it manually to the proper location resolved the issue for me, but the build script probably needs to be updated to place this in the proper directory (or the instructions need to be updated to explain how to tell it the proper location).

**Comment by RiQuY** [comment]
Same behaviour in my system, openSUSE Tumbleweed too.

**Comment by dimtpap** [comment]
It should default to the correct one now. If not, set `CMAKE_INSTALL_LIBDIR` during the config step.
