### ISSUE TITLE
Release 1.1.4 is actually 1.1.3

### ISSUE THREAD

**Issue by flexiondotorg** [dimtpap/obs-pipewire-audio-capture#52]
Release 1.1.4 is built from commit https://github.com/dimtpap/obs-pipewire-audio-capture/commit/0805939191532504903c80b2ae6560f9838cc27a which is the same commit 1.1.3 was built from on Jan 21st 2024.

**1.1.4**

![image](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/304639/108b3e11-320f-4cfe-8bbe-89731528649e)

**1.1.3**

![image](https://github.com/dimtpap/obs-pipewire-audio-capture/assets/304639/022d4cf7-5de9-411e-ab3d-e7cd807cba18)

**Comment by dimtpap** [comment]
it is, but has been rebuilt against OBS 28. 1.1.3 was built against OBS 30. Is it causing issues?

**Comment by flexiondotorg** [comment]
No issue; I just noticed when I revved the package (built from source) for NixOS that the hash didn't change, which is irregular :slightly_smiling_face: 

I'll close this; it causes no issues.
