### ISSUE TITLE
Not detecting any applications (other than itself)

### ISSUE THREAD

**Issue by slxdy** [dimtpap/obs-pipewire-audio-capture#59]
So I have the latest versions of this plugin and WirePlumber installed, as well as OBS. I'm running the latest version of Linux Mint on the latest kernel version.

For whatever reason, the plugin only detects `obs`, `wireplumber`, and `xdg-desktop-portal`. Inputting the binary name does nothing. My end goal is to capture the audio from Team Fortress 2, but so far I haven't even been successful with capturing the audio from Chrome.

**Comment by dimtpap** [comment]
Is `pipewire-pulse` installed? 
README has more info, under the Requirements section

**Comment by slxdy** [comment]
Yes

**Comment by BrianENguyen** [comment]
Not OP but I'm having the same problem as well. Here's my log file:

https://obsproject.com/logs/cdzYSRMqusVdVwht

**Comment by dimtpap** [comment]
What's the output of `pactl info`

**Comment by dimtpap** [comment]
@BrianENguyen You need pipewire-pulse, based on the log it isn't set up properly.
