### ISSUE TITLE
Application not in dropdown if no audio is played (during alt tab) - offer optional setting as workaround?

### ISSUE THREAD

**Issue by zaggynl** [dimtpap/obs-pipewire-audio-capture#6]
Scenario 1: start game 1 (https://store.steampowered.com/app/1611910/Warhammer_40000_Chaos_Gate__Daemonhunters/) via Steam Proton, start obs, select application source, game is not listed in dropdown as game pauses everything including audio when not focused.

Scenario 2: start game 2 (https://store.steampowered.com/app/1604030/V_Rising/)  via Steam Proton, start obs, select application source, game is listed in dropdown as does not pause, audio playback (music) continues when not focused.

Workaround: offer optional setting in plugin that allows selection of applications currently not playing audio?

**Comment by dimtpap** [comment]
Will do
