### ISSUE TITLE
(REQ) Update multi capture source to OBS 30.2

### ISSUE THREAD

**Issue by EmersonBiggons** [dimtpap/obs-pipewire-audio-capture#61]
First, I don't want this to seem like a demand. I definitely need this update, but I also understand life is life and this is a hobby not a job.

Anyway, I hope you find the time to update it as I cannot live without the Multi capture version. It saves too much time and does too much heavy lifting that I can't realistically live without it. I'm sure many others would agree.

Hope you are well, thank you for your hard work, regardless of if you update it or not. <3

**Comment by dimtpap** [comment]
https://github.com/dimtpap/obs-pipewire-audio-capture/issues/24#issuecomment-2231655993
