### ISSUE TITLE
SDL2's "pipewire" driver causes audio dropouts.

### ISSUE THREAD

**Issue by KynikossDragonn** [dimtpap/obs-pipewire-audio-capture#64]
For some reason if SDL2 is allowed to use it's native PipeWire driver my "Desktop Audio" capture starts dropping like crazy, but there's no errors showing up in `pw-top` or the terminal I'm running OBS from.

All I can really show for this is my entire VOD starting from this timestamp: https://www.twitch.tv/videos/2202059222?t=0h13m22s

My previous VODs were okay and the only thing I recently updated was PipeWire itself; which is now at version 1.2.1 at the time of this issue report.

**Comment by dimtpap** [comment]
1.1.5 fixed stuff like this, update the plugin if you haven't in the last 6 days

**Comment by KynikossDragonn** [comment]
I tried recompiling the plugin from the latest commit before I wrote this issue, it made no difference.

If I set `SDL_AUDIODRIVER=alsa` before launching SDL2 using applications the problem doesn't happen, but that doesn't make any sense why that would fix it.

**Comment by dimtpap** [comment]
Does this happen with the [`pw-record`](https://docs.pipewire.org/page_man_pw-cat_1.html) program?

**Comment by KynikossDragonn** [comment]
> Does this happen with the [`pw-record`](https://docs.pipewire.org/page_man_pw-cat_1.html) program?

It does, but even with verbose `pw-record` output I'm not getting any error messages of any kind, not even of underruns but it does sound like it's underunning?

This is starting to feel like a PipeWire regression itself, very confusing...
[pw-record.log.gz](https://github.com/user-attachments/files/16325236/pw-record.log.gz)

**Comment by dimtpap** [comment]
Sounds very much like a regression with PipeWire 1.2.1 then. You should report [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues)
