### ISSUE TITLE
Add multiple filters

### ISSUE THREAD

**Issue by corngoblin** [dimtpap/obs-pipewire-audio-capture#66]
Can you possibly change it up to where we can filter more than 1 source like so or something similar?
![Screenshot from 2024-07-28 02-54-39](https://github.com/user-attachments/assets/5fcfa1a3-edc2-491c-9190-83ad45c60e83)

I'd like to filter off firefox, discord and strawberry and pick up everything else so I can tweak the audio of those separate.

Right now, I can only do 1 with how it works at the moment.

Thank you for your time and for the great plugin.

**Comment by dimtpap** [comment]
See #24
