### ISSUE TITLE
Steam Deck compatibility

### ISSUE THREAD

**Issue by rocket0634** [dimtpap/obs-pipewire-audio-capture#68]
Hello, I just installed the flatpak version of OBS and downloaded the flatpak plugin for pipewire audio capture, and it appears to not be functioning properly.
The plugin will allow me to select apps to capture and select devices to capture respectively, but once the source is added, no audio is captured.
Additionally, the screen capture option also does not appear to be working properly. It appears that the steam deck comes with WirePlumber, Pipewire, and Pipewire-pulse included. And it appears my pipewire version is 0.3.62.

I have tried to capture audio for a game and for Discord, and neither appear to be doing anything.

Is there more set up I need to do for this?

**Comment by alterNERDtive** [comment]
> And it appears my pipewire version is 0.3.62.

For starters, that is almost 2y out of date.

**Comment by rocket0634** [comment]
> > And it appears my pipewire version is 0.3.62.
> 
> For starters, that is almost 2y out of date.

It's the minimum version stated in the readme.

**Comment by dimtpap** [comment]
There's a problem with OBS's Flatpak runtime PipeWire + old PipeWire version on the host https://github.com/dimtpap/obs-pipewire-audio-capture/issues/54

Your screen capture problem is caused by https://github.com/obsproject/obs-studio/issues/10409

**Comment by rocket0634** [comment]
Okay, is there anything I need to do here or do I need to wait for this to be fixed on OBS's end?

**Comment by dimtpap** [comment]
> Okay, is there anything I need to do here or do I need to wait for this to be fixed on OBS's end?

You can install a newer PipeWire on the host

**Comment by rocket0634** [comment]
I imagine that is possible, but the steam deck does not support installing libraries directly to the system. It is managed by valve software, and any update to the system would result in items not installed in /home being overwritten. This is why the steam deck only allows for flatpak installs. 

Additionally I read in my searches that valve uses pipewire for important features on the steam deck, which means updating it outside of that could cause other issues. 

So while I can disable the lock valve put on the steam deck, I wanted to open this issue for the general user of the steam deck who would wish to stream steam games via obs.

Outside of the obvious waiting for valve to update their packages, I'd imagine this would need to be handled on obs's side
