### ISSUE TITLE
Crash on add source

### ISSUE THREAD

**Issue by AlbinoGeek** [dimtpap/obs-pipewire-audio-capture#7]
Hello,

OBS crashes to desktop (Fedora 36) whenever I try to add one of these pipewire sources.

Here's the error (only shown when OBS run from terminal):

```
[E] pw.context [pipewire.c:256 load_spa_handle()] load lib: plugin directory undefined, set SPA_PLUGIN_DIR
[E] pw.loop [loop.c:83 pw_loop_new()] 0x560b08944810: can't make support.system handle: No such file or directory
'obs' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by MurdoMaclachlan** [comment]
Getting the same error over here (Slackware Current), `OBS_USE_EGL=1 obs` makes no difference for me.

My error log has a slight difference, with the final line just being `Segmentation fault` instead.

Notably, it's only happening with 1.0.0 for me; if I roll back to the last version before that, it works fine. I also note, with 1.0.0 installed, none of my existing PipeWire sources from the older version do anything, and their 'Properties' options are greyed out.

**Comment by dimtpap** [comment]
Hopefully it's happening because I just forgot to call pw_init, can you try [this build](https://github.com/dimtpap/obs-pipewire-audio-capture/files/9000363/linux-pipewire-audio-callpwinit.tar.gz)?

**Comment by MurdoMaclachlan** [comment]
No more crashing and the video sources are fully working again, but the existing audio sources still have 'Properties' greyed out and don't appear in the audio mixer or record any audio. Newly-added audio sources work as expected.

Interestingly, for existing audio sources with filters, the 'Filters' menu is still acessible, but looks like this:

![image](https://user-images.githubusercontent.com/47920497/176173218-17006d32-9b90-4dbb-b18c-5d9f016440cc.png)

Only displays one filter, with no option to change to others (though I know others do exist for it) or add/remove ones.
