### ISSUE TITLE
Application and Match Priority options absent

### ISSUE THREAD

**Issue by simon-anderson** [dimtpap/obs-pipewire-audio-capture#70]
Fedora 40, OBS 30.2.2 Flatpak install.

Copying the flatpak archive of the plugin to /var/lib/flatpak/runtime/ seems to work, **Audio Input Capture (PulseAudio)** and **Audio Output Capture (Pulse Audio)** are selectable sources.

 However the Properties popup does not provide an option to choose the **Application** and **Match Priority**. The only option presented is to select the device.

What am I doing wrong?
![Screenshot from 2024-08-05 02-01-08](https://github.com/user-attachments/assets/13da52ee-f35d-46d7-880f-9ef441fb59df)

**Comment by dimtpap** [comment]
Wrong sources. You're looking for "Application Audio Capture (PipeWire)".

**Comment by simon-anderson** [comment]
Okay. The issue is then, that the **Application Audio Capture (PipeWire)** source is not available in the sources menu, using the configuration and installation method I described in the OP. The other two are, and they wok.

Any guidance you can give me on rectifying greatly appreciated.
