### ISSUE TITLE
 Application Audio Capture (PipeWire) Source not created

### ISSUE THREAD

**Issue by simon-anderson** [dimtpap/obs-pipewire-audio-capture#71]
Fedora 40, Wayland, OBS 30.2.2 Flatpak install.

Following the readme install instructions **Audio Input Capture (PulseAudio)** and **Audio Output Capture (Pulse Audio)** are selectable sources and both work as expected.

However a **Application Audio Capture (PipeWire)** source is not created.

![Screenshot from 2024-08-06 01-26-48](https://github.com/user-attachments/assets/2a99eac7-7695-42ba-b1e7-5388be76fbe1)

**Comment by AlphSpirit** [comment]
Make sure you download the -flatpak version from this page: https://github.com/dimtpap/obs-pipewire-audio-capture/releases

**Comment by simon-anderson** [comment]
Hello AlphSpirit,

Thank you for your response. That is the package I'm using.

**Comment by simon-anderson** [comment]
**FIX**

For anyone else using Fedora 40, the solution is to copy linux-pipewire-audio.so from the archive to:

/var/lib/flatpak/app/com.obsproject.Studio/x86_64/stable/<SOME LONG STRING>/files/lib/obs-plugins/

**Comment by simon-anderson** [comment]
Closed

**Comment by alterNERDtive** [comment]
> For anyone else using Fedora 40, the solution is to copy linux-pipewire-audio.so from the archive to:
> 
> /var/lib/flatpak/app/com.obsproject.Studio/x86_64/stable//files/lib/obs-plugins/

Or install OBS as a user Flatpak (which you should probably do anyway).
