### ISSUE TITLE
Application Audio Capture won't read my applications

### ISSUE THREAD

**Issue by EdwyTheChen-Pug** [dimtpap/obs-pipewire-audio-capture#76]
Hello, and thank you in advance.
I run Debian and have installed `obs-studio` from the testing source (30.2.3.1-2 right now) and also installed `obs-pipewire-audio-capture` (1.1.5-1+b1) from the same source.
I am able to add Application Audio Capture to my list of sources, but it doesn't let me actually choose an audio source.
![image](https://github.com/user-attachments/assets/17959637-ca63-4957-b5c7-cf63dae378a1)
No option to change the window.
I have `pipewire`, `wireplumber`, `pipewire-pulse`, `pipewire-jack`, and `pipewire-alsa` installed. And I am certain I'm not accidentally choosing another option, like Audio Input Capture, like some people in the issues tab mistakenly have.
I am a noob at pirewire so I am not quite sure what I'm supposed to do.
[****](https://obsproject.com/logs/oo8xSOlpAHL7PGwW)
Here is my current OBS log file as well.

**Comment by dimtpap** [comment]
Looks like it can't connect to the PipeWire daemon. What's the output of `pactl info`?

https://wiki.debian.org/PipeWire#Debian_12 has instructions on how to set up everything

**Comment by dimtpap** [comment]
Server name should say "pulseaudio (on pipewire x.y.z)". PipeWire is not running, see the setup instructions for your distro
