### ISSUE TITLE
The plugin is constantly killing and recreating its connection endlessly.

### ISSUE THREAD

**Issue by KynikossDragonn** [dimtpap/obs-pipewire-audio-capture#78]
I don't know how else to describe this but today when I load up OBS the plugin keeps non-stop ending its capture and restarting it every one and a half second; wireplumber's CPU usage is going insane as well.

I'm running the following under Void Linux:
```
$ wireplumber --version
wireplumber
Compiled with libwireplumber 0.5.6
Linked with libwireplumber 0.5.6
```

```
$ pipewire --version
pipewire
Compiled with libpipewire 1.2.6
Linked with libpipewire 1.2.6
```

It wasn't doing this before my system updated to the latest wireplumber and pipewire releases. I'm not sure what's going on. Can't downgrade either.

[logs.zip](https://github.com/user-attachments/files/17758048/logs.zip)

**Comment by dimtpap** [comment]
Fixed WirePlumber bug, the thread contains a workaround. https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/715
