### ISSUE TITLE
Window Titles for Applications

### ISSUE THREAD

**Issue by AlbinoGeek** [dimtpap/obs-pipewire-audio-capture#8]
Hello!

Since you fixed my last issue so quickly, I can now use the plugin!

It works well, except, I can't really tell what I'm recording without trial-and-error.

See the following input lists for Application Capture:

![image](https://user-images.githubusercontent.com/1910461/176242719-ab24b2f8-57ab-4324-b44d-8c45e60cf26c.png)

**Comment by dimtpap** [comment]
Selecting one "Firefox" will record all Firefox streams. I'll have to see how to make it so only one entry appears in the list

**Comment by AlbinoGeek** [comment]
> Selecting one "Firefox" will record all Firefox streams. I'll have to see how to make it so only one entry appears in the list

Which is curious when they all have their own Sink IDs / Source IDs. I'm glad you're already aware of this issue however. In the meantime, I can compile multiple Firefox installations with different process names, as a temporary workaround.

**Comment by dimtpap** [comment]
It is an application's responsibility to report properties like Window Title, if it wants, to PipeWire and not all do, so filtering based on those properties isn't really feasible.

**Comment by AlbinoGeek** [comment]
You are right. Fedora 36 update is what broke this. Pavucontrol also doesn't show window titles anymore.

Feodra 35 though, I could see window titles. I suppose I need to complain to Fedora devs now, haha.
